# Environment level secrets
# create the env prod, qa, staging etc and create secretes for each
# In order to use environment inside GitHub workflow, we just have to use this property environments and specify the name of environment to which we want to deploy our workflow
#

name: github env secreets

# Controls when the workflow will run
on: workflow_dispatch

jobs:
  # This workflow contains a single job called "build"
  github-secret:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://docs.github.com
    steps:
      - uses: actions/checkout@v3

      
      - name: print secret from prod environment
      # first it will check the value of the secret in the environment that we have specified, if the secret value is found in the environment, it will take it from there. If it is not found in the environment, then it will go ahead and take the value of this secret from the repository level secret
        run: |
          echo "Env Secret : ${{secrets.GIT_ACTIONS_SECRET_TEST_PROD}}" 
 
