# This is a basic workflow to help you get started with Actions

name: github secreets

# Controls when the workflow will run
on: workflow_dispatch

jobs:
  # This workflow contains a single job called "build"
  github-secret:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: print secret
        run: |
          echo "Env Secret : ${{secrets.GIT_ACTIONS_SECRET_TEST}}"
          echo "Repo Secret : ${{secrets.GIT_ACTIONS_SECRET_TEST_REPO}}"

      - name: print secret as an env variable
        run: |
          echo "Env_Creds: $Env_Creds"
          echo "Repo_Creds: $Repo_Creds"
        
        env:
          Env_Creds: ${{secrets.GIT_ACTIONS_SECRET_TEST}}
          Repo_Creds: ${{secrets.GIT_ACTIONS_SECRET_TEST_REPO}}
        
